version: '3.8'

services:
  error-service:
    build: 
      context: ./backend/services/error
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
    networks:
      - app-network
    depends_on:
      - rabbitmq

  pay-for-delivery:
    build: 
      context: ./backend/services/pay-for-delivery
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - orderURL=http://order-service:5001/order
      - walletURL=http://wallet-service:3000  
      - errorURL=http://error-service:5002
    networks:
      - app-network
    depends_on:
      - wallet-service
      - rabbitmq

  wallet-service:
    build: 
      context: ./backend/services/wallet
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DEBUG=false
      - PORT=3000
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
      - RABBITMQ_HOST=rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge